var TRANSLATION = {
  lang: 'en',
  fallback_lang: 'en',
  en: {
    askBtn: 'Ask',
    nameInput: 'Name',
    fromInput: 'From',
    toInput: 'To',
    messageInput: 'Message',
    sendBtn: 'Send',
    cancelBtn: 'Cancel',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    deleteBtn: 'delete all questions',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation',
    replyBtn: 'reply'
  },
  ua: {
    askBtn: 'Запитати',
    nameInput: 'ім`я',
    fromInput: 'місто',
    messageInput: 'повідомлення',
    sendBtn: 'надіслати',
    cancelBtn: 'відмінити',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  sv: {
    askBtn: 'Ställ fråga',
    nameInput: 'Namn',
    fromInput: 'Ort',
    messageInput: 'Meddelande',
    sendBtn: 'Skicka',
    cancelBtn: 'Avbryt',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  sl: {
    askBtn: 'Vprašanje',
    nameInput: 'Ime',
    fromInput: 'Kraj bivanja',
    messageInput: 'Sporočilo',
    sendBtn: 'Pošlji',
    cancelBtn: 'Prekliči',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  ro: {
    askBtn: 'Întrebare',
    nameInput: 'Nume',
    fromInput: 'Localitate',
    messageInput: 'Mesaj',
    sendBtn: 'Trimite',
    cancelBtn: 'Anulează',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  pt: {
    askBtn: 'Perguntar',
    nameInput: 'Nome',
    fromInput: 'Localização',
    messageInput: 'Mensagem',
    sendBtn: 'Enviar',
    cancelBtn: 'Cancelar',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  pl: {
    askBtn: 'Zadaj pytanie',
    nameInput: 'Imię',
    fromInput: 'Miejscowość',
    messageInput: 'Wiadomość',
    sendBtn: 'Wyślij',
    cancelBtn: 'Anuluj',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  no: {
    askBtn: 'Still spørsmål',
    nameInput: 'Navn',
    fromInput: 'Sted',
    messageInput: 'Melding',
    sendBtn: 'Send',
    cancelBtn: 'Avbryt',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  mk: {
    askBtn: 'Постави прашање',
    nameInput: 'Име ',
    fromInput: 'Место',
    messageInput: 'Порака',
    sendBtn: 'Прати',
    cancelBtn: 'Откажи',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  lt: {
    askBtn: 'Pateikti klausimą',
    nameInput: 'Vardas',
    fromInput: 'Miestas',
    messageInput: 'Klausimas',
    sendBtn: 'Siųsti',
    cancelBtn: 'Atšaukti',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  lv: {
    askBtn: 'Jautāt',
    nameInput: 'Vārds',
    fromInput: 'No kurienes',
    messageInput: 'Ziņa',
    sendBtn: 'Sūtīt',
    cancelBtn: 'Atcelt',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  it: {
    askBtn: 'Fai una domanda',
    nameInput: 'Nome',
    fromInput: 'Città',
    messageInput: 'Messaggio',
    sendBtn: 'Invio',
    cancelBtn: 'Cancella',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  hu: {
    askBtn: 'Kérdés feltevése',
    nameInput: 'Név',
    fromInput: 'Helyzet',
    messageInput: 'Üzenet',
    sendBtn: 'Küldés',
    cancelBtn: 'Törlés',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  de: {
    askBtn: 'Frage stellen',
    nameInput: 'Name',
    fromInput: 'Ort',
    messageInput: 'Botschaft',
    sendBtn: 'Abschicken',
    cancelBtn: 'Abbrechen',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  fr: {
    askBtn: 'Poser une question',
    nameInput: 'Nom',
    fromInput: 'Ville, pays',
    messageInput: 'Message',
    sendBtn: 'Envoyer',
    cancelBtn: 'Annuler',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  nl: {
    askBtn: 'Stel een vraag',
    nameInput: 'Naam',
    fromInput: 'Woonplaats',
    messageInput: 'Bericht',
    sendBtn: 'Verzenden',
    cancelBtn: 'Annuleren',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  bg: {
    askBtn: 'Задайте въпрос',
    nameInput: 'Име',
    fromInput: 'Град',
    messageInput: 'Въпрос',
    sendBtn: 'Изпрати',
    cancelBtn: 'Отмени',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  hr: {
    askBtn: 'Postavi pitanje',
    nameInput: 'Ime',
    fromInput: 'Grad',
    messageInput: 'Pitanje',
    sendBtn: 'Pošalji',
    cancelBtn: 'Poništi',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },  
  cz: {
    askBtn: 'Položit otázku',
    nameInput: 'Jméno',
    fromInput: 'Město',
    messageInput: 'Zpráva',
    sendBtn: 'Pošalji',
    cancelBtn: 'Poništi',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  },    
  es: {
    askBtn: 'Pregunta',
    nameInput: 'Nombre',
    fromInput: 'Localidad',
    messageInput: 'Mensaje',
    sendBtn: 'Enviar',
    cancelBtn: 'Cancelar',
    removeBtn: 'remove',
    disallow: 'rechazar',
    allow: 'permitir' ,
    dir: 'ltr',
    exportBtn: 'export'
  },
  ru: {
    askBtn: 'спросить',
    nameInput: 'Имя',
    fromInput: 'Город',
    messageInput: 'Ваше сообщение',
    sendBtn: 'Послать',
    cancelBtn: 'Отменить',
    removeBtn: 'удалить',
    disallow: 'отказать',
    allow: 'одобрить',
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Модерация'
  },
  he: {
    askBtn: 'לשאול',
    nameInput: 'שם',
    fromInput: 'מ',
    messageInput: 'הודעה',
    sendBtn: 'לשלוח',
    cancelBtn: 'לבטל',
    removeBtn: 'להסיר',
    disallow: 'לפסול',
    allow: 'להתיר',
    dir: 'rtl',
    exportBtn: 'export'
  },
  tr: {
    askBtn: 'Soru Sor',
    nameInput: 'İsim',
    fromInput: 'Şehir',
    messageInput: 'Mesaj',
    sendBtn: 'Gönder',
    cancelBtn: 'İptal',
    removeBtn: 'remove',
    disallow: 'disallow',
    allow: 'allow' ,
    dir: 'ltr',
    exportBtn: 'export',
    autoApproveBtn: 'auto approve',
    messTitleAdmin: 'Moderation'
  } 
};

